-- Ejecutar en Supabase SQL Editor, después de las migraciones anteriores.
--
-- "Capital inicial" (o cartera con la que arrancó el negocio): el monto con el
-- que el cobrador empezó a operar el negocio (no es la base diaria de la caja,
-- que cambia cada día — este es el punto de partida histórico, de una sola vez).
-- Se guarda en preferencias_usuario, junto al resto de ajustes del negocio.
alter table public.preferencias_usuario add column if not exists capital_inicial numeric;
alter table public.preferencias_usuario add column if not exists capital_inicial_fecha date;

-- Historial de cambios al capital inicial, por si se corrige más de una vez
-- (por ejemplo, si se escribió mal la primera vez). Queda un registro fechado
-- de cada valor anterior, igual que ya existe para el orden de rutas.
create table if not exists public.historial_capital_inicial (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  monto_anterior numeric,
  monto_nuevo numeric not null,
  cambiado_en timestamptz not null default now()
);

alter table public.historial_capital_inicial enable row level security;
drop policy if exists "Usuarios ven su historial de capital inicial" on public.historial_capital_inicial;
create policy "Usuarios ven su historial de capital inicial" on public.historial_capital_inicial for select using (user_id = auth.uid());
drop policy if exists "Usuarios crean su historial de capital inicial" on public.historial_capital_inicial;
create policy "Usuarios crean su historial de capital inicial" on public.historial_capital_inicial for insert with check (user_id = auth.uid());
