-- Ejecutar en Supabase SQL Editor, después de las migraciones anteriores.
--
-- A veces el cobrador mete plata de su propio bolsillo (no de la cartera del
-- negocio) para completar un préstamo, por ejemplo. Esto guarda esos aportes
-- por separado de los cobros normales, para no mezclarlos ni confundirlos en
-- los reportes — la caja diaria (js/main.js) los suma aparte al calcular el
-- efectivo esperado del día.

create table if not exists public.aportes_capital (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  fecha date not null,
  monto numeric not null check (monto > 0),
  nota text,
  creado_en timestamptz not null default now()
);

create index if not exists aportes_capital_fecha_idx on public.aportes_capital (user_id, fecha);

alter table public.aportes_capital enable row level security;
drop policy if exists "Usuarios ven sus aportes" on public.aportes_capital;
create policy "Usuarios ven sus aportes" on public.aportes_capital for select using (user_id = auth.uid());
drop policy if exists "Usuarios crean sus aportes" on public.aportes_capital;
create policy "Usuarios crean sus aportes" on public.aportes_capital for insert with check (user_id = auth.uid());
drop policy if exists "Usuarios borran sus aportes" on public.aportes_capital;
create policy "Usuarios borran sus aportes" on public.aportes_capital for delete using (user_id = auth.uid());
