-- Ejecutar en Supabase SQL Editor, después de las migraciones anteriores.

-- Permite etiquetar (opcionalmente) cada gasto con la ruta a la que
-- pertenece. Antes todos los gastos quedaban "sueltos", sin poder saber si
-- la gasolina o el gasto de tal día fue de una ruta en particular o del
-- negocio en general. Queda NULL = "general / no aplica a una ruta".
-- Nota: la caja diaria (caja_diaria) queda intencionalmente sin este campo —
-- representa un solo efectivo físico del cobrador, no una caja por ruta.
alter table public.gastos add column if not exists ruta_id bigint references public.rutas(id) on delete set null;
create index if not exists gastos_ruta_idx on public.gastos (ruta_id);

-- Guarda la "suscripción" que el navegador/celular crea para poder recibir
-- notificaciones push reales (aunque la app esté cerrada). Cada dispositivo
-- donde el cobrador active las notificaciones agrega su propia fila.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  creado_en timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;
drop policy if exists "Usuarios ven sus suscripciones push" on public.push_subscriptions;
create policy "Usuarios ven sus suscripciones push" on public.push_subscriptions for select using (user_id = auth.uid());
drop policy if exists "Usuarios crean sus suscripciones push" on public.push_subscriptions;
create policy "Usuarios crean sus suscripciones push" on public.push_subscriptions for insert with check (user_id = auth.uid());
drop policy if exists "Usuarios borran sus suscripciones push" on public.push_subscriptions;
create policy "Usuarios borran sus suscripciones push" on public.push_subscriptions for delete using (user_id = auth.uid());

-- Pequeña tabla de preferencias por usuario. Por ahora solo guarda si alguna
-- vez activó el bloqueo con PIN (para poder recordárselo si un día abre la
-- app en un celular nuevo, o después de reinstalarla, y el PIN local ya no
-- está — ver js/bloqueo.js). El PIN en sí NUNCA se guarda aquí, solo el
-- indicador de "sí uso esta protección".
create table if not exists public.preferencias_usuario (
  user_id uuid primary key references auth.users(id) on delete cascade,
  pin_activado_alguna_vez boolean not null default false,
  actualizado_en timestamptz not null default now()
);

alter table public.preferencias_usuario enable row level security;
drop policy if exists "Usuarios ven sus preferencias" on public.preferencias_usuario;
create policy "Usuarios ven sus preferencias" on public.preferencias_usuario for select using (user_id = auth.uid());
drop policy if exists "Usuarios crean sus preferencias" on public.preferencias_usuario;
create policy "Usuarios crean sus preferencias" on public.preferencias_usuario for insert with check (user_id = auth.uid());
drop policy if exists "Usuarios actualizan sus preferencias" on public.preferencias_usuario;
create policy "Usuarios actualizan sus preferencias" on public.preferencias_usuario for update using (user_id = auth.uid());
